env:
  global:
  - secure: ZFXtDAGP+KHupVLCzAY9sldXt/1NEJ6wrNc7JoBe+oXpLFkkQwI0NQBGD7F7cOpza/Dt2PYeQR9f0GkuumPLNWRgwjZwZkt5nDNRX0L78Rj13nhKHZk99IGZ4SStVSLb/kLWloedqts3Ml4hVAlwZzdCGmsrZShPaRQclvArsoj36LwO3xA2Ob7jy6AnKSC53BbIdHastHQwGM0lxQLYH5k5RLOj2TBKmQuk6E3E3Kq1/VBeSgZ/4fedgMFqmSWjAGxNGPHTi9Kua0rq5hQb+tRBAawWZSpM1ZTQUc877KPloqHOp39w990Fw4MQZqhk5JawVv1m4Jm4dSoXUrSMgFxQZp0gDXYAdTnvVHoy3m6hK1bXiJmAry8SlgUehQeaD3Zke72bglX3Z5beIfgA7yv719Lr6uoKgHyqN8cV2l6yWkAVNhDqROr6I17ynDMqxsXwfbGqLojdLbXvf4tuNKoK9n6Ffv7+AnyHroWikzCbebDzg+HekKksEQ2vt1dzQkkhA8BULPodb4DAiHL2F+1EKO3i2pnHjOldu7lA8fwGfV/BdYxpeN/EosmJg2srpdivlTj4s+Eb3YiZRC9LyVeLnEPuh47bnK6hrsoKFJ0AiM/aLrXplI28k+Q2YP7GQIFZEOGSFpFx4LcovrOjB+uOCs5ay9R96aYTncfxzkg=
  - secure: Kafr5GmfCqJ9muC9XlAiGMTaDoPbObx+duaWi4ovh5CTru0RfsMenQwgKhEn/H/6X47HxBTyfTttiiusPKZtX7EaoQY/7SrrCChpFbAt8PcNAlJbYsov6aKgeZvbphrMfVhMlfJK+fN7ql6Q45SIFJCysLOI8x1c1nUq5IYG1nVt/iKX7ZEIXa1DKF4IDTB0oWcDwYH7HfHtnCoW09cDdwAt1SJNvuc2zOeN0pF5xa4Neno3JOAzk7qpp3N2h7uC2vuPJY7OPcEBKGa1aho+uuYzSAOnKRNohllX11sWTgXyuQIbcDJJCRZy8HcZfeO1QZVR8lpIv4+HiBjuN4gQKTrHBCXP7JdAsSkMdfRzrMz+TKBDKr689e+3YYSMejOHn2Sn53M/YIkJUYDD263j4cxw7irXAZxT/xkOOSZZP3ta74ZWoN/a0q3n1NEg8sWaARcZMvP1BYzgyDbOadDvdPzv56+PnI1OVXnSXEdHnryAl1UZwStMpgWAL42qfjZWZSrnS+UEBtIhuEDsu79oMlgkUiG4yQuJQ/V3HcqoeNgLXriTwFIRA04MGhdjXnw3/AJhkgRGv91R654Nt0j0wYwjy3LGUMH4XOm/X13oVTlFDDcZWAqYumVsA/7th/SUIu7Eq+d126sRXPa/FcCAmAsfkXcAkG6GiOgVjfpz1q8=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: o5Ao0eKlAQkWjkWfgBfFkmdrZHQfX2lnIwDcgPim8REOk5f3H8nfbXTeCWzsxWTxAJ1tklmySkweJxv3r3f08J8ShHd6R6K+m+/2jFkcyWnv/N0qqiodMiUDHdYFKX8D351Ydq6jYEvy0Lha2Om64+gMAhedS5H2GiCxrUjY0wDMNyz86WEvf2j8G2zIUNHQ5I9jAosImz+CGMvlDIva2CcBJ/mW96dKoGYzLx4D+lxenBCj37bOIGd2TLod7qxJdEirjdaX9D3QV8WvYIhKXnDTf3bEakf9u1mvF7nwmhxTFRhbORFuIbeKKU0yOpIkzXwBF5XTXAkn//bFfvJTXA/v3lxXfQepqJe8XwO5TYTBQq7MbQoc1ViO6c6Asi8+03aLQGO7OAs+5GrnEa1TcWzuaixJjviTY0XOMUar6bOLoWGmGpBWVTqkWcPa2lMxMPSVNQrVHbbanbMBgRnbfEI64+KAxVCDPD8PcjMNbk3RD33FDosf/BOJKKhA53T4o/OmJ9fSdDQsiZBJTKxBH3bsJCXetb9oUIX9nzC0Fjm8PJ4Q2ZN5NOVcV+yUCCHN9xuHPBNiYjXu3fYrylAbtEABeEPvZhYp4ZihNIGUSiZhpy3EhFWP0isUXh7lJS4AYywZvhVXLtSZqi0/P871r3Br263RogueXiz0/Kr5lV0=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild:10sp5

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild:10sp5
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: V+lBXC2BYPNDSgqsQoQaqFpJvQy/wWT2W/AON3b7SChfSaqXmPunq9rhej0JLFibQlkO6gyUVyRTPYGRH2PM409mNdTwVIKrLWHqpsJ0x8maVdUIyK8NcTgbIh3OMH9NLxgADyzMQMOyq2dP+gpBSV/oxYvc+OqcUkXyw984gHBmE1b13YppOQcW8I0hOj6q7ylWdHmAAqvH6xMOjwt3UHhHnONB6tE6TnxbbPfD5xzM3iY5Tzp5aEROS+KxBvxBI3tsP9jhrVgBXaixfHVN0ZYDS4GDIBLZPqeQipurbZ9EpDsP0EokhpBzSWlE/5TXRN1ohp1ZJEA/ETcG6XFq3JS6FrEZtaqenzADGoYUrnAI4xnwYvV+ock825yFiAd/xXME/XdoPLONkr/riq1dk21WTm1lyAqGvTr8VVlfqSrM/Wt+6hysgHEtCIQsMUMmV6z09IoYdO4GCZ1Za75A+Ru4pAFsKhLyeOVT3CLNfgzEuQz0rY0YbMRQXRI7khpoIObycNBC/Q7G0yCoKu1RTshjV3TgaUyLdFahbZdICANmolHRcvpOiKozvrOJkrd3XPai6M7rRf/KXR+OpzMPekIBElbOR/a7WEHr21MBVLqbn695Td34453+JhuTG2MtNMV1esI4s/oXjyb+VkSeX0fQU/lHGfZIAK0fOOF7oxQ=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
